FROM python:3.8
WORKDIR /mydir
RUN pip3 install numpy
RUN pip3 install matplotlib
RUN pip3 install pandas
RUN pip3 install seaborn
RUN pip3 install sklearn
RUN pip3 install tensorflow
ENTRYPOINT ["python3"]
